#!/usr/bin/env bash

# Config
MARKETS=WETH-RDN,WETH-OMG
MNEMONIC='candy maple cake sugar pudding cream honey rich smooth crumble sweet treat'
ETHEREUM_RPC_URL=https://rinkeby.infura.io
RDN_TOKEN_ADDRESS=0x3615757011112560521536258c1e7325ae3b48ae
OMG_TOKEN_ADDRESS=0x00df91984582e6e96288307e9c2f20b38c8fece9
DX_SERVICE_VERSION=staging

[ -f local.conf ] && source local.conf || echo "WARN: local.conf file wasn't found. Using default config"

# Get the params
CLI_PARAMS=${@:--h}

echo
echo "  *********  Dutch X CLI - $DX_SERVICE_VERSION  *********"
echo "    Operation: $CLI_PARAMS"
echo "    Markets: $MARKETS"
echo "    Ethereum Node: $ETHEREUM_RPC_URL"
echo "  *********************************"
echo

docker run \
  -e MNEMONIC="$MNEMONIC" \
  -e ETHEREUM_RPC_URL=$ETHEREUM_RPC_URL \
  -e MARKETS=$MARKETS \
  -e RDN_TOKEN_ADDRESS=$RDN_TOKEN_ADDRESS \
  -e OMG_TOKEN_ADDRESS=$OMG_TOKEN_ADDRESS \
  -e DEBUG_HIDE_DATE=true \
  -e DEBUG_COLORS=true \
  -e NODE_ENV="pre" \
  gnosispm/dx-services:$DX_SERVICE_VERSION \
  npm run --silent cli -- $CLI_PARAMS
