#!/usr/bin/env bash

# Config
DX_SERVICE_VERSION=staging # Check: https://hub.docker.com/r/gnosispm/dx-services/tags/
MNEMONIC="super secret thing that nobody should know"
MARKETS=WETH-RDN
RDN_TOKEN_ADDRESS=0x3615757011112560521536258c1e7325ae3b48ae
OMG_TOKEN_ADDRESS=0x00df91984582e6e96288307e9c2f20b38c8fece9
ETHEREUM_RPC_URL=https://rinkeby.infura.io
NETWORK=rinkeby
ENVIRONMENT=pre # local, pre, pro
SHOW_COLORS=true
DEBUG_MESSAGES=DEBUG=ERROR-*,WARN-*,INFO-*,DEBUG-dx-service:services:*,DEBUG-dx-service:repositories:PriceRepo*
#DEBUG_MESSAGES=DEBUG=ERROR-*,WARN-*,INFO-*,DEBUG-*
#DEBUG_MESSAGES=DEBUG=ERROR-*,WARN-*,INFO-*

# Get the params
CLI_PARAMS=${@:--h}

DOCKER_IMAGE="gnosispm/dx-services:$DX_SERVICE_VERSION"
APP_COMMAND="yarn cli $CLI_PARAMS"

[ -f local.conf ] && source local.conf || echo "WARN: local.conf file wasn't found. Using default config"

echo
echo "  *********  DutchX CLI - $DX_SERVICE_VERSION  *********"
echo "    Operation: $CLI_PARAMS"
echo "    Markets: $MARKETS"
echo "    Ethereum Node: $ETHEREUM_RPC_URL"
echo "  *********************************"
echo
echo "[cli] Getting docker image: $DOCKER_IMAGE..."
docker pull $DOCKER_IMAGE

echo
docker run \
  -p 8081:8081 \
  -e MNEMONIC="$MNEMONIC" \
  -e NETWORK="$NETWORK" \
  -e MARKETS=$MARKETS \
  -e RDN_TOKEN_ADDRESS=$RDN_TOKEN_ADDRESS \
  -e OMG_TOKEN_ADDRESS=$OMG_TOKEN_ADDRESS \
  -e ETHEREUM_RPC_URL=$ETHEREUM_RPC_URL \
  -e NODE_ENV=$ENVIRONMENT \
  -e DEBUG=$DEBUG_MESSAGES \
  -e NODE_ENV=$ENVIRONMENT \
  -e DEBUG_COLORS=$SHOW_COLORS \
  $DOCKER_IMAGE \
  $APP_COMMAND
